_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: 'gpu-device-plugins.yaml,node-feature-rules.yaml'
backups: false
helm: true
helmCrds: false
helmName: intel-device-plugins-operator
helmRelease: intel-device-plugins-operator
helmRepo: https://intel.github.io/helm-charts/
helmValues: helm/values.yaml
helmVersion: '0.34.0'
homepageEnabled: false
ingress: false
labels: ''
name: intel-device-plugins-operator
namespace: intel-device-plugins
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://www.intel.com/content/www/us/en/developer/articles/technical/device-plugins-operator.html
url: https://github.com/charlesthomas/homelab-intel-device-plugins-operator
