_commit: v1.8.1
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: intel-device-plugins-operator
helmRelease: intel-device-plugins-operator
helmRepo: https://intel.github.io/helm-charts/
helmValues: helm/values.yaml
helmVersion: ''
homepageEnabled: true
ingHost: intel-device-plugins-operator.crt.house
ingName: intel-device-plugins-operator
ingress: false
labels: ''
name: intel-device-plugins-operator
namespace: intel-device-plugins-operator
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://www.intel.com/content/www/us/en/developer/articles/technical/device-plugins-operator.html
url: https://github.com/charlesthomas/homelab-intel-device-plugins-operator
