---
apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: intel-gpu-device-plugin
spec:
  image: "intel/intel-gpu-plugin:0.34.0"
  logLevel:  2
  sharedDevNum: 1
  enableMonitoring: true
  preferredAllocationPolicy: none
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
